=== derjasper/ResponsiveMarkup/libs/responsivemarkup/definition/default.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://bluetreehouse.de"
           xmlns="http://bluetreehouse.de"
           xmlns:xhtml="http://www.w3.org/1999/xhtml"
>
    
    <!-- HTML subset -->
    
    <xs:import namespace="http://www.w3.org/1999/xhtml" schemaLocation="./xhtml1-strict.xsd"/> 
    
    <xs:element name="ul" substitutionGroup="xhtml:ul"/>
    <xs:element name="li" substitutionGroup="xhtml:li"/>
    <xs:element name="strong" substitutionGroup="xhtml:strong"/>
    <xs:element name="a" substitutionGroup="xhtml:a"/>
    <xs:element name="table" substitutionGroup="xhtml:table"/>
    <xs:element name="tr" substitutionGroup="xhtml:tr"/>
    <xs:element name="th" substitutionGroup="xhtml:th"/>
    <xs:element name="td" substitutionGroup="xhtml:td"/>
    
    <!-- TODO make sure that responsivemarkup is always root, think of what to do with the html subset ... -->
    <!-- TODO html attribute verbieten -->
    
    <xs:attribute name="area-id" type="xs:string"/> 
    
    <!-- root -->
    
    <xs:element name="responsivemarkup">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="section" type="section" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <!-- blocks -->
    
    <xs:complexType name="section">        
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="content" type="container_any_list"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="imageandtext">
        <xs:sequence>
            <xs:element name="image" type="image" />
            <xs:element name="textblock" type="textblock" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="row">
        <xs:choice minOccurs="1" maxOccurs="4">
            <xs:element name="column" type="column" />
        </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="column">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="content" type="container_simple_list"/>
        </xs:sequence>
    </xs:complexType>
        
        
    <xs:complexType mixed="true" name="textblock">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="ul"/>
            <xs:element ref="strong"/>
            <xs:element ref="table"/>
            <xs:element ref="a"/>
        </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="image">
        <xs:attribute name="src">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[a-zA-Z0-9]+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute> 

        <xs:attribute name="description" type="xs:string"/>
    </xs:complexType>
    
    
    <!-- types -->
    
    <xs:complexType name="container_any_list">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="textblock" type="textblock" />
            <xs:element name="image" type="image" />
            <xs:element name="section" type="section" />
            <xs:element name="row" type="row" />
            <xs:element name="imageandtext" type="imageandtext" />
        </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="container_simple_list">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="textblock" type="textblock" />
            <xs:element name="image" type="image" />
        </xs:choice>
    </xs:complexType>

</xs:schema>

=== derjasper/ResponsiveMarkup/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<responsivemarkup
    xmlns="http://bluetreehouse.de"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://bluetreehouse.de ./libs/responsivemarkup/definition/default.xsd"
>
    <section>
        <title>Title</title>
        <content>
            <section>
                <title>Title</title>
                <content>
                    <textblock>
                        <strong>content</strong>
                        <table>
                            <tr>
                                <th>th</th>
                                <td>td</td>
                            </tr>
                        </table>
                    </textblock>
                    
                    <row area-id="test">
                        <column>
                            <title>Title</title>
                            <content>
                                <textblock>Hallo</textblock>
                            </content>
                        </column>
                        <column>
                            <title>Title</title>
                            <content>
                                <textblock>Hallo</textblock>
                            </content>
                        </column>
                    </row>
                </content>
            </section>
            <section>
                <title>Title 2</title>
                <content>
                    <imageandtext>
                        <image src="test" description="CC-BY-SA 2.0, (c) Martin Fisch, https://flic.kr/p/oaicc1" />
                        <textblock>
                            Test 1
                        </textblock>
                    </imageandtext>
                    <imageandtext>
                        <image src="test" description="CC-BY-SA 2.0, (c) Martin Fisch, https://flic.kr/p/oaicc1" />
                        <textblock>
                            Test 2
                        </textblock>
                    </imageandtext>
                    <imageandtext>
                        <image src="test" description="CC-BY-SA 2.0, (c) Martin Fisch, https://flic.kr/p/oaicc1" />
                        <textblock>
                            Test 3
                        </textblock>
                    </imageandtext>
                </content>
            </section>
        </content>
    </section>
</responsivemarkup>
